DOMAIN = "wakepsx_on_bt"
CONF_CONTROLER_BT_ADDRESS = "dsbt_address"
CONF_PLAYSTATION_BT_ADDRESS = "psxbt_address"
SERVICE_SEND_MAGIC_PACKET = "send_magic_packet"
SERVICE_GET_BT_ADDR = "get_bt_addr"
CONF_ADAPTER = "adapter"
WOBTPSX_PREFIX = "PsxBt."
