send_magic_packet:
  fields:
    adapter:
      required: true
      example: "hci0"
      default: "hci0"
      selector:
        text:
    dsbt_address:
      example: "aa:bb:cc:dd:ee:ff"
      selector:
        text:
    psxbt_address:
      example: "aa:bb:cc:dd:ee:ff"
      selector:
        text:

get_bt_addr: